kind: pipeline
type: docker
name: default
steps:
  - name: build
    image: golang:alpine
    commands:
      - go env -w GOPROXY=https://goproxy.cn,direct
      - GOOS=linux GOARCH=amd64 go build -o shorten
  - name: publish
    depends_on:
      - build
    image: plugins/docker
    pull: if-not-exists
    settings:
      registry: hub.ccw.es
      username:
        from_secret: nexus_docker_username
      password:
        from_secret: nexus_docker_password
      repo: hub.ccw.es/home/shorten
      tags:
        - ${DRONE_COMMIT_SHA:0:8}
        - latest
