kind: pipeline
type: docker
name: default
steps:
  - name: build
    image: golang:alpine
    commands:
      - go env -w GOPROXY=https://goproxy.cn,direct
      - GOOS=linux GOARCH=amd64 go build -o shorten
  - name: publish
    depends_on:
      - build
    image: plugins/docker
    pull: if-not-exists
    settings:
      registry: hub.ccw.es
      username:
        from_secret: nexus_docker_username
      password:
        from_secret: nexus_docker_password
      repo: hub.ccw.es/home/shorten
      tags:
        - ${DRONE_COMMIT_SHA:0:8}
        - latest
  - name: deploy
    image: appleboy/drone-ssh
    depends_on:
      - build_docker
    settings:
      host:
        from_secret: k8s_host
      username:
        from_secret: k8s_username
      key:
        from_secret: k8s_key
      port: 22
      command_timeout: 2m
      script:
        - echo ${DRONE_COMMIT}${DRONE_BUILD_NUMBER}
        - kubectl apply -f https://git.ccw.es/ccw/yaml/raw/branch/master/shorten.yaml
        - kubectl set image deployment/shorten shorten=hub.ccw.es/home/shorten:${DRONE_COMMIT_SHA:0:8}
